"""splent_feature_tools

Revision ID: ebc0d7bc3483
Revises: 
Create Date: 2026-06-27 22:24:45.080768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc0d7bc3483'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=512), nullable=True),
    sa.Column('github', sa.String(length=512), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_slug'), 'tool', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_slug'), table_name='tool')
    op.drop_table('tool')
    # ### end Alembic commands ###
